### ISSUE TITLE
Make Clarin centres linkable in format recommendations

### ISSUE THREAD

**Issue by margaretha** [clarin-eric/standards#185] opened 2023-02-21 10:51 UTC
The [format recommendation](https://clarin.ids-mannheim.de/standards/views/recommended-formats-with-search.xq) table has a Clarin centre column. As centres now have description pages, it would be handy to have them link to their pages.

**Comment by bansp** [comment] 2023-02-21 11:06
Absolutely. Thanks, Eliza! :-)

**Comment by bansp** [comment] 2023-02-25 23:02
Ah, it's actually a duplicate of #153 -- and that rather conveniently places the fix in Eliza's hands, what's not to like about that! :-)

**Comment by bansp** [comment] 2023-03-03 11:02
Closing as duplicate, assigned Eliza to the other one.

**Closed by bansp** 2023-03-03 11:02 UTC
Labels: duplicate, enhancement
